language: go

sudo: false

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install: make prereqs

script:
  - go get ./...
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
