site_name: cbft Technical Documentation (0.0 DP)

pages:
- ['index.md', 'Home']
- ['dev-guide/overview.md', "Developer's Guide", "Developer's guide overview"]
- ['dev-guide/concepts.md', "Developer's Guide", "Key concepts"]
- ['dev-guide/index-definitions.md', "Developer's Guide", "Index definitions"]
- ['dev-guide/index-queries.md', "Developer's Guide", "Index queries"]
- ['dev-guide/performance.md', "Developer's Guide", "Performance"]
- ['api-ref.md', "API Reference"]
- ['admin-guide/overview.md', "Administrator's Guide", "Administrator's guide overview"]
- ['admin-guide/command.md', "Administrator's Guide", "cbft command-line"]
- ['admin-guide/planning.md', "Administrator's Guide", "Planning your deployment"]
- ['admin-guide/running.md', "Administrator's Guide", "Running cbft"]
- ['admin-guide/clustering.md', "Administrator's Guide", "Clustering cbft"]
- ['admin-guide/managing.md', "Administrator's Guide", "Managing cbft"]
- ['admin-guide/monitoring.md', "Administrator's Guide", "Monitoring cbft"]
- ['admin-guide/diagnosing.md', "Administrator's Guide", "Diagnosing issues"]
- ['links.md', "Links"]

copyright: Copyright &copy; 2015, <a href="http://couchbase.com">Couchbase, Inc.</a>.

theme: flatly